apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  selector:
    matchLabels:
      app: user-service
      tier: microservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user-service
        tier: microservice
    spec:
      containers:
      - name: user-service
        image: atolpeko/user-service:1.0
        ports:
          - containerPort: 3070
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: SERVER_PORT
          value: "3070"  
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: user-service-secret
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: user-service-secret
              key: db-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-service-secret
              key: db-password
        - name: SPRING_SECURITY_OAUTH2_JWT-KEY
          valueFrom:
            secretKeyRef:
              name: user-service-secret
              key: jwt-key      
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
    tier: microservice
spec:
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 6060
      targetPort: 3070
  selector:
    app: user-service 
    tier: microservice
    